### ISSUE TITLE
Install Error on Big Sur 11.6 Mac M1

### ISSUE THREAD

**Issue by daBee** [ruby-opencv/ruby-opencv#107]
This gem and `opencv` have similar installation issues.  `Ruby 2.7.3`.  

		Installing ruby-opencv 0.0.18 with native extensions
		Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

				current directory: /Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/opencv-0.0.7/ext
		/Users/rich/.rbenv/versions/2.7.3/bin/ruby -I /Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0 -r ./siteconf20211025-28525-b01lkf.rb extconf.rb
		/Users/rich/.rbenv/versions/2.7.3/bin/ruby: warning: shebang line ending with \r may cause problems
		>> check require libraries...
		checking for -lcxcore... no
		*** extconf.rb failed ***
		Could not create Makefile due to some reason, probably lack of necessary
		libraries and/or headers.  Check the mkmf.log file for more details.  You may
		need configuration options.

		Provided configuration options:
			--with-opt-dir
			--without-opt-dir
			--with-opt-include
			--without-opt-include=${opt-dir}/include
			--with-opt-lib
			--without-opt-lib=${opt-dir}/lib
			--with-make-prog
			--without-make-prog
			--srcdir=.
			--curdir
			--ruby=/Users/rich/.rbenv/versions/2.7.3/bin/$(RUBY_BASE_NAME)
			--with-opencv-dir
			--without-opencv-dir
			--with-opencv-include
			--without-opencv-include=${opencv-dir}/include
			--with-opencv-lib
			--without-opencv-lib=${opencv-dir}/lib
			--with-ffcall-dir
			--without-ffcall-dir
			--with-ffcall-include
			--without-ffcall-include=${ffcall-dir}/include
			--with-ffcall-lib
			--without-ffcall-lib=${ffcall-dir}/lib
			--with-cxcore-dir
			--without-cxcore-dir
			--with-cxcore-include
			--without-cxcore-include=${cxcore-dir}/include
			--with-cxcore-lib
			--without-cxcore-lib=${cxcore-dir}/lib
			--with-cxcorelib
			--without-cxcorelib
		extconf.rb:32:in `block in <main>': libcxcore not found. (RuntimeError)
			from extconf.rb:31:in `each'
			from extconf.rb:31:in `<main>'

		To see why this extension failed to compile, please check the mkmf.log which can be found here:

			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/extensions/arm64-darwin-20/2.7.0/opencv-0.0.7/mkmf.log

		extconf failed, exit code 1

		Gem files will remain installed in /Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/opencv-0.0.7 for inspection.
		Results logged to /Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/extensions/arm64-darwin-20/2.7.0/opencv-0.0.7/gem_make.out

			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tempfile.rb:291:in `open'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in build_extension'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in build_extensions'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/rubygems_gem_installer.rb:66:in `build_extensions'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/rubygems_gem_installer.rb:26:in `install'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/source/rubygems.rb:199:in `install'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/installer/gem_installer.rb:54:in `install'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/worker.rb:62:in `apply_func'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/worker.rb:57:in `block in process_queue'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/worker.rb:54:in `loop'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/worker.rb:54:in `process_queue'
			/Users/rich/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.2.29/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

		An error occurred while installing opencv (0.0.7), and Bundler cannot continue.

Here is that make log file:

		have_library: checking for -lcxcore... -------------------- no

		"clang -o conftest -I/Users/rich/.rbenv/versions/2.7.3/include/ruby-2.7.0/arm64-darwin20 -I/Users/rich/.rbenv/versions/2.7.3/include/ruby-2.7.0/ruby/backward -I/Users/rich/.rbenv/versions/2.7.3/include/ruby-2.7.0 -I. -I/usr/local/include -I/usr/local/include/opencv -I/Users/rich/.rbenv/versions/2.7.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -fno-common -pipe conftest.c  -L. -L/Users/rich/.rbenv/versions/2.7.3/lib -L/usr/local/lib -L. -L/Users/rich/.rbenv/versions/2.7.3/lib  -fstack-protector-strong  -m64   -lruby.2.7   "
		checked program was:
		/* begin */
		1: #include "ruby.h"
		2:
		3: int main(int argc, char **argv)
		4: {
		5:   return !!argv[argc];
		6: }
		/* end */

		"clang -o conftest -I/Users/rich/.rbenv/versions/2.7.3/include/ruby-2.7.0/arm64-darwin20 -I/Users/rich/.rbenv/versions/2.7.3/include/ruby-2.7.0/ruby/backward -I/Users/rich/.rbenv/versions/2.7.3/include/ruby-2.7.0 -I. -I/usr/local/include -I/usr/local/include/opencv -I/Users/rich/.rbenv/versions/2.7.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -fno-common -pipe conftest.c  -L. -L/Users/rich/.rbenv/versions/2.7.3/lib -L/usr/local/lib -L. -L/Users/rich/.rbenv/versions/2.7.3/lib  -fstack-protector-strong  -m64   -lruby.2.7 -lcxcore   "
		ld: library not found for -lcxcore
		clang: error: linker command failed with exit code 1 (use -v to see invocation)
		checked program was:
		/* begin */
		 1: #include "ruby.h"
		 2:
		 3: /*top*/
		 4: extern int t(void);
		 5: int main(int argc, char **argv)
		 6: {
		 7:   if (argc > 1000000) {
		 8:     int (* volatile tp)(void)=(int (*)(void))&t;
		 9:     printf("%d", (*tp)());
		10:   }
		11:
		12:   return !!argv[argc];
		13: }
		14:
		15: int t(void) { ; return 0; }
		/* end */

I am assuming the OS, the version, the hardware, and native libraries are pulling a fast one.  Not sure how to move forward.  

Cheers

**Comment by DerekCrosson** [comment]
Did you end up resolving this? I have the same issue but on MacOS Sonoma, same hardware specs

**Comment by daBee** [comment]
Can't even remember.  Two years ago.

**Comment by adentaofftake** [comment]
did anyone end up resolving this? lol
