### ISSUE TITLE
errors installing - opencv 4.7.0, ruby 3.1, ubuntu 22.04

### ISSUE THREAD

**Issue by JLanghauser** [ruby-opencv/ruby-opencv#108]
I'm not even sure if this repo is still maintained, but wanted to post this just in case. 

```
$ gem install ruby-opencv
Building native extensions. This could take a while...
ERROR:  Error installing ruby-opencv:
	ERROR: Failed to build gem native extension.

    current directory: /home/john/.rvm/gems/ruby-3.1.0/gems/ruby-opencv-0.0.18/ext/opencv
/home/john/.rvm/rubies/ruby-3.1.0/bin/ruby extconf.rb
>> Check the required libraries...
checking for -lstdc++... yes
checking for -lopencv_calib3d... yes
checking for -lopencv_contrib... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/john/.rvm/rubies/ruby-3.1.0/bin/$(RUBY_BASE_NAME)
	--with-opencv-dir
	--without-opencv-dir
	--with-opencv-include
	--without-opencv-include=${opencv-dir}/include
	--with-opencv-lib
	--without-opencv-lib=${opencv-dir}/lib
	--with-libxml2-dir
	--without-libxml2-dir
	--with-libxml2-include
	--without-libxml2-include=${libxml2-dir}/include
	--with-libxml2-lib
	--without-libxml2-lib=${libxml2-dir}/lib
	--with-stdc++-dir
	--without-stdc++-dir
	--with-stdc++-include
	--without-stdc++-include=${stdc++-dir}/include
	--with-stdc++-lib
	--without-stdc++-lib=${stdc++-dir}/lib
	--with-stdc++lib
	--without-stdc++lib
	--with-opencv_calib3d-dir
	--without-opencv_calib3d-dir
	--with-opencv_calib3d-include
	--without-opencv_calib3d-include=${opencv_calib3d-dir}/include
	--with-opencv_calib3d-lib
	--without-opencv_calib3d-lib=${opencv_calib3d-dir}/lib
	--with-opencv_calib3dlib
	--without-opencv_calib3dlib
	--with-opencv_contrib-dir
	--without-opencv_contrib-dir
	--with-opencv_contrib-include
	--without-opencv_contrib-include=${opencv_contrib-dir}/include
	--with-opencv_contrib-lib
	--without-opencv_contrib-lib=${opencv_contrib-dir}/lib
	--with-opencv_contriblib
	--without-opencv_contriblib
extconf.rb:58:in `block in <main>': opencv_contrib not found. (RuntimeError)
	from extconf.rb:58:in `each'
	from extconf.rb:58:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/john/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/ruby-opencv-0.0.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/john/.rvm/gems/ruby-3.1.0/gems/ruby-opencv-0.0.18 for inspection.
Results logged to /home/john/.rvm/gems/ruby-3.1.0/extensions/x86_64-linux/3.1.0/ruby-opencv-0.0.18/gem_make.out
```

**Comment by DanBradbury** [comment]
did you build `opencv` from source?

I'm currently running into the same issue after I install with `brew install opencv` (https://formulae.brew.sh/formula/opencv#default). At this moment in time it looks like 4.9 is the stable version

`gem install ruby-opencv -- --with-opencv-dir=/opt/homebrew/Cellar/opencv/4.9.0_12`

I can try to downgrade later from source but thats been [disabled by brew because of no upstream maintenance](https://formulae.brew.sh/formula/opencv@3)

```
» brew install opencv@3
Error: opencv@3 has been disabled because it is not maintained upstream!
```

Would be nice to have ruby bindings work in 4.X and am just arriving to this project today
