### ISSUE TITLE
mingw版でdllが見つからない

### ISSUE THREAD

**Issue by jirihin** [ruby-opencv/ruby-opencv#18]
はじめまして。
以前から仕事でも使わせてもらっています。
irbからopencvが使えて幸せです。

gem でリモートから取れるようになったと聞いたので試したのですが、
以下のようなメッセージが出てうまくいきません。

C:>ruby -v
ruby 1.9.3p392 (2013-02-22) [i386-mingw32]

C:>gem list ruby-opencv

**\* LOCAL GEMS ***

ruby-opencv (0.0.8 x86-mingw32)

C:>ruby -e 'require "opencv"'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require':
126: 指定されたモジュールが見つかりません。   - C:/Ruby193/lib/ruby/gems/1.9.1/g
ems/ruby-opencv-0.0.8-x86-mingw32/lib/opencv.so (LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:i
n`rescue in require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:i
n `require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/ruby-opencv-0.0.8-x86-mingw32/l
ib/opencv.rb:2:in`<top (required)>'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:i
n `require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:i
n`rescue in require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:i
n `require'
        from -e:1:in`<main>'

dllのパスは確認しています。
opencvは、2.4.3、2.4.2で試しました。
以前のように手でパスを与える方法とかありますか？

**Comment by KojiKobayashi** [comment]
Wndows7 64bit、opencv2.4.10、vc10　の環境でインストールしようとしたところ、
二つオプションが必要でしたが、以下でうまくいきました。
```
gem install ruby-opencv --platform ruby -- --with-opencv-include=C:/opencv2410/build/include/ --with-opencv-lib=C:/opencv2410/build/x86/vc10/lib/
```

オプションなしだと、
```
extconf.rb:16:in `initialize': No such file or directory @ rb_sysopen - /usr/loc
al/include/opencv2/core/version.hpp (Errno::ENOENT)
```
こんな感じで怒られました。
パスの解決がうまくいってないように思います。

**Comment by ser1zw** [comment]
@KojiKobayashi ご報告いただき、ありがとうございます。
vc10ということは、お使いのRubyはmswin版ということですね。

ご指摘のとおり、最近のruby-opencvでは後述の理由によりWindows用のビルド済みgemが
配布できておらず、常に自前でのビルドが必要になるため、
--with-opencv-includeと--with-opencv-libでのオプション指定が必要になります
（このあたりREADMEの記載が追いついていないです。すみません…）。

パスが自動的に見つけられないのは、特にWindowsでは、OpenCVをインストールするパスが
想定しづらいという事情によるものです。
MacやLinuxだと/usr/local以下が比較的多いと思いますが、WindowsだとC:\直下に置く人とか、
C:\Program Filesとか、さらにはフォルダ名にOpenCVのバージョンをつけたりとか、
無数に考えられるので…。

ビルド済みgemが配布できていない理由というのは、実はmswin版ではビルドできるものの
mingw版（というかRubyInstaller）ではパスを指定してもうまくいかないケースがあるというものです。
原因はRubyInstallerとOpenCVのビルド環境の差異にありそうなのですが、解決にはちょっと
大変そうで、まだ対応できていないというのが実情です。

**Comment by n-oshiro** [comment]
こんにちは。

RubyInstaller (x64-mingw32)
で、ruby-opencvをインストールしようとしたら、はまりまして、OpenCV2の構築からやり直してなんとか成功しましたので、お知らせします。

gem install 時に使われる DevKit の 'x86_64-w64-mingw32-g++' では正しく opencv.so
がリンクできないようで、MinGW64を別途インストールして、gem install時にそちらを使うように設定しました。

Rubyバージョン: Ruby interpreter (CUI) 2.1.5p273 [x64-mingw32]
OS: Windows 7 Home Premium 64bit

1. OpenCV2 を入手：


https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.11/opencv-2.4.11.exe/download

  これを 'C:\opencv2' へ展開。

2. MinGW64 (mingw64-installer.exe) を入手：

  http://sourceforge.net/projects/mingw-w64/
  http://sourceforge.net/projects/mingw-w64/files/latest/download

  これを、下記の設定で C:\MinGW64 へインストール：

  Architecture: 'x86_64' (not sure which option is better).
  Thread: 'posix' (not sure which option is better)
  Destination folder: 'C:\MinGW64'

3. OpenCV2 コンパイル用に CMake (http://www.cmake.org/) でMakefileを生成：

  Source code: C:/opencv2/sources
  Binaries: C:/opencv2/build/x64/mingw

  'Configure' 時に 'native compilers' として下記を指定：

  C COMPILER: C:/MinGW64/mingw64/bin/gcc.exe
  CXX_COMPILER: C:/MinGW/mingw64/bin/g++.exe
  Fortran_COMPILER: C:/MinGW64/mingw64/bin/gfortran.exe

  再度、'Configure'し、その後 'Generate' で Makefile を生成.

4. OpenCV2 をコンパイルし、'build\x64\mingw' ディレクトリへ生成.

  C:\> PATH=C:\MinGW64\mingw64\bin;%PATH%
  C:\> cd C:\opencv2\build\x64\mingw
  C:\> mingw32-make install

5. 'gem install' 時に DevKit でなく、MinGW64 を使うように
$(RUBY)\lib\ruby\site_ruby\devkit.rb 内で設定変更（使われる make が DevKit
にしかなかったので、DevKitへのパスも後ろに残しています。）

--- devkit.rb.orig   2015-08-16 14:52:52.634904300 +0900
+++ devkit.rb  2015-08-16 14:52:06.875287000 +0900
@@ -1,15 +1,15 @@
 # enable RubyInstaller DevKit usage as a vendorable helper library
-unless ENV['PATH'].include?('C:\\devkit\\mingw\\bin') then
-  phrase = 'Temporarily enhancing PATH to include DevKit...'
+unless ENV['PATH'].include?('C:\\MinGW64\\ming64\\bin') then
+  phrase = 'Temporarily enhancing PATH to include MinGW64...'
   if defined?(Gem)
     Gem.ui.say(phrase) if Gem.configuration.verbose
   else
     puts phrase
   end
-  puts "Prepending ENV['PATH'] to include DevKit..." if $DEBUG
-  ENV['PATH'] = 'C:\\devkit\\bin;C:\\devkit\\mingw\\bin;' + ENV['PATH']
+  puts "Prepending ENV['PATH'] to include MinGW64..." if $DEBUG
+  ENV['PATH'] = 'C:\\MinGW64\mingw64\\bin;C:\\devkit\\bin;' + ENV['PATH']
 end
-ENV['RI_DEVKIT'] = 'C:\\devkit'
+ENV['RI_DEVKIT'] = 'C:\\MinGW64\\ming64'
 ENV['CC'] = 'gcc'
 ENV['CXX'] = 'g++'
 ENV['CPP'] = 'cpp'
---

  （または、新規に 'mingw64.rb' ファイルを上記のdiff
結果の内容で生成して同じディレクトリに置き、rubygems/defaults の 'operating_system.rb' で
'devkit.rb' の代わりに読み込むように指定する).

6. Gem インストール.

  C:\> gem install ruby-opencv --verbose --platform=ruby --
--with-opencv-include=C:\opencv2\build\include
--with-opencv-lib=C:\opencv2\build\x64\mingw\lib

7. ruby-opencv サンプル実行

  C:\> PATH=C:\opencv2\build\x64\mingw\bin;%PATH%
  (さらに、PATH に MinGW64 バイナリへの 'C:\MinGW64\mingw64\bin' が含まれるようにすること（参考：手順4.）)
  C:\> cd C:\Ruby21-x64\lib\ruby\gems\2.1.0\gems\ruby-opencv-0.0.14\examples
  C:\> ruby alpha-blend.rb
  ('face-detect.rb' は、始めは Haar data ディレクトリが存在しなくて実行できず、このディレクトリを OpenCV2の
examples ディレクトリからコピーしても正しく動作しませんでした）。




2015年2月13日 0:37 ser1zw <notifications@github.com>:

> @KojiKobayashi <https://github.com/KojiKobayashi> ご報告いただき、ありがとうございます。
> vc10ということは、お使いのRubyはmswin版ということですね。
>
> ご指摘のとおり、最近のruby-opencvでは後述の理由によりWindows用のビルド済みgemが
> 配布できておらず、常に自前でのビルドが必要になるため、
> --with-opencv-includeと--with-opencv-libでのオプション指定が必要になります
> （このあたりREADMEの記載が追いついていないです。すみません…）。
>
> パスが自動的に見つけられないのは、特にWindowsでは、OpenCVをインストールするパスが
> 想定しづらいという事情によるものです。
> MacやLinuxだと/usr/local以下が比較的多いと思いますが、WindowsだとC:\直下に置く人とか、
> C:\Program Filesとか、さらにはフォルダ名にOpenCVのバージョンをつけたりとか、
> 無数に考えられるので…。
>
> ビルド済みgemが配布できていない理由というのは、実はmswin版ではビルドできるものの
> mingw版（というかRubyInstaller）ではパスを指定してもうまくいかないケースがあるというものです。
> 原因はRubyInstallerとOpenCVのビルド環境の差異にありそうなのですが、解決にはちょっと
> 大変そうで、まだ対応できていないというのが実情です。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-opencv/ruby-opencv/issues/18#issuecomment-74091145>
> .
>



-- 
=============================================
OSHIRO Naoki: oshiro@mibai.tec.u-ryukyu.ac.jp
http://mibai.tec.u-ryukyu.ac.jp/~oshiro/

**Comment by ser1zw** [comment]
情報ありがとうございます。
OpenCVとruby-opencvの両方をMinGW64でコンパイルするということですね。
確かにこれであればうまくいくかもしれません。

こちらでこれまでに調べていた範囲では、OpenCV自体をDevKitのg++でコンパイルして、
パスの通ったところに libstdc++ 等を置けば動作するのですが、この場合の配布方法を
どうしようか…というところで対応できていない状況でした。
引き続き、ご連絡頂いた方法を含めて検討してみますね。
