### ISSUE TITLE
Invalid sequence error. (TypeError)

### ISSUE THREAD

**Issue by julianmaster** [ruby-opencv/ruby-opencv#78]
Hi,

I have a issue with the `CvSeq` method when I browse a tree from `find_contours`

```
require "opencv"
require 'pp'
include OpenCV

image = OpenCV::CvMat.new(100, 100, OpenCV::CV_8U, 1).fill(0)
image[10,50] = OpenCV::CvColor::White
image[20,50] = OpenCV::CvColor::White
image[30,50] = OpenCV::CvColor::White
image[40,50] = OpenCV::CvColor::White
image[50,50] = OpenCV::CvColor::White


def contourTreeToList(parent)
    list = Array.new()
    _contourTreeToList(parent, list)
    return list
end

def _contourTreeToList(node, list)
    list.push(node)
    
    if node.v_next != nil
        _contourTreeToList(node.v_next, list) 
    end
    
    if node.h_next != nil
        _contourTreeToList(node.h_next, list) 
    end
end

#error Invalid sequence error.
1_000_000.times do |i|
    contours = image.find_contours(:mode => CV_RETR_TREE)
    list = contourTreeToList(contours)
end
```

When this script is run, Ruby show the error message like

```
test.rb:26:in `h_next': Invalid sequence error. (TypeError)
	from test.rb:26:in `_contourTreeToList'
	from test.rb:27:in `_contourTreeToList'
	from test.rb:27:in `_contourTreeToList'
	from test.rb:27:in `_contourTreeToList'
	from test.rb:14:in `contourTreeToList'
	from test.rb:35:in `block in <main>'
	from test.rb:33:in `times'
	from test.rb:33:in `<main>'
```

I use Ruby 2.2.4 with OpenCV 2.4.11 on Ubuntu 14.04 LTS
ruby-opencv 0.0.16 install with RubyGems

Regards,

**Comment by ser1zw** [comment]
Thank you for your reporting.
I fixed this problem at 4684a20cdfb53fef41af9db9ad724141ae2da8fe .
