### ISSUE TITLE
gem install failure in mac 10.11

### ISSUE THREAD

**Issue by totothink** [ruby-opencv/ruby-opencv#79]
i run below command:
```shell
$ brew install opencv3 --with-contrib --with-cuda --with-ffmpeg --with-tbb --with-qt5
```

opencv3 be installed in /usr/local/opt/opencv3.

i run below command:
```shell
$ gem install ruby-opencv -- --with-opencv-dir=/usr/local/opt/opencv3
```

error:
```shell
This could take a while...
ERROR:  Error installing ruby-opencv:
	ERROR: Failed to build gem native extension.

    current directory: /Users/aaron/.rvm/gems/ruby-2.3.0/gems/ruby-opencv-0.0.16/ext/opencv
/Users/aaron/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160610-24783-4c3lqb.rb extconf.rb --with-opencv-dir=/usr/local/opt/opencv3/
>> Check the required libraries...
checking for main() in -lstdc++... yes
checking for main() in -lopencv_calib3d... yes
checking for main() in -lopencv_contrib... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/aaron/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--with-opencv-dir
	--with-opencv-include
	--without-opencv-include=${opencv-dir}/include
	--with-opencv-lib
	--without-opencv-lib=${opencv-dir}/lib
	--with-libxml2-dir
	--without-libxml2-dir
	--with-libxml2-include
	--without-libxml2-include=${libxml2-dir}/include
	--with-libxml2-lib
	--without-libxml2-lib=${libxml2-dir}/lib
	--with-stdc++lib
	--without-stdc++lib
	--with-opencv_calib3dlib
	--without-opencv_calib3dlib
	--with-opencv_contriblib
	--without-opencv_contriblib
extconf.rb:58:in `block in <main>': opencv_contrib not found. (RuntimeError)
	from extconf.rb:58:in `each'
	from extconf.rb:58:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/aaron/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/ruby-opencv-0.0.16/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/aaron/.rvm/gems/ruby-2.3.0/gems/ruby-opencv-0.0.16 for inspection.
Results logged to /Users/aaron/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-15/2.3.0/ruby-opencv-0.0.16/gem_make.out
```

environment:
os: mac 10.11
ruby: 2.3.0

**Comment by ser1zw** [comment]
Hi,

Unfortunately ruby-opencv does not support OpenCV 3 right now.
It supports OpenCV 2, so try using OpenCV 2.

Additionally, I'm working on OpenCV 3 support at https://github.com/ruby-opencv/ruby-opencv/tree/experimental/opencv3 branch.
It supports only a few functions right now, but I'll add functions from now.
