### ISSUE TITLE
Missing local dependency after brew install opencv on gem install (checking for main() in -lopencv_contrib... no)

### ISSUE THREAD

**Issue by gastongouron** [ruby-opencv/ruby-opencv#95]
OSX Sierra / 10.12.5 / MacBook Pro (Retina, 13-inch, Early 2015)
running `brew install opencv` (I have python installed already)
then running `gem install ruby-opencv`
results in the following error when looking for required dependancies: 
`>> Check the required libraries...
checking for main() in -lstdc++... yes
checking for main() in -lopencv_calib3d... yes
checking for main() in -lopencv_contrib... no`

Assuming I'm missing some dependancies, do I need to speicfy a version when brew installing? 
I run the exact same error when running -- --with-path-to-opencv pointing to the last version manually refferrenced. 

Any help truly appreciated.

Full trace:
```
gem install ruby-opencv
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-opencv:
	ERROR: Failed to build gem native extension.

    current directory: /Users/paulgastongouron/.rvm/gems/ruby-2.3.1/gems/ruby-opencv-0.0.18/ext/opencv
/Users/paulgastongouron/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20171016-99772-y0sp7b.rb extconf.rb
>> Check the required libraries...
checking for main() in -lstdc++... yes
checking for main() in -lopencv_calib3d... yes
checking for main() in -lopencv_contrib... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/paulgastongouron/.rvm/rubies/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
	--with-opencv-dir
	--without-opencv-dir
	--with-opencv-include
	--without-opencv-include=${opencv-dir}/include
	--with-opencv-lib
	--without-opencv-lib=${opencv-dir}/lib
	--with-libxml2-dir
	--without-libxml2-dir
	--with-libxml2-include
	--without-libxml2-include=${libxml2-dir}/include
	--with-libxml2-lib
	--without-libxml2-lib=${libxml2-dir}/lib
	--with-stdc++lib
	--without-stdc++lib
	--with-opencv_calib3dlib
	--without-opencv_calib3dlib
	--with-opencv_contriblib
	--without-opencv_contriblib
extconf.rb:58:in `block in <main>': opencv_contrib not found. (RuntimeError)
	from extconf.rb:58:in `each'
	from extconf.rb:58:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/paulgastongouron/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/ruby-opencv-0.0.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/paulgastongouron/.rvm/gems/ruby-2.3.1/gems/ruby-opencv-0.0.18 for inspection.
Results logged to /Users/paulgastongouron/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-16/2.3.0/ruby-opencv-0.0.18/gem_make.out
```

**Comment by barrywoolgar** [comment]
I think you may have installed OpenCV 3 instead of 2. Try `brew install opencv@2`, and then use `gem install ruby-opencv --with-opencv-dir=/usr/local/opt/opencv@2`. 

As I'm using Bundler, I had to run:

`bundle config build.ruby-opencv --with-opencv-dir=/usr/local/opt/opencv@2`

before running `bundle install` to set the build option.

**Comment by gastongouron** [comment]
Thank you very much. I ended up doing this project with Node. The wrapper is way better :)

**Comment by mnyrop** [comment]
Stumbled here with a similar problem, so thought I'd share my experience for future googlers. 

The above answer gave me an `invalid option` error but running $ `brew link opencv@2 --force` and then $ `echo 'export PATH="/usr/local/opt/opencv@2/bin:$PATH"' >> ~/.zshrc` worked for me. (just make sure to echo into whatever .rc you're using.)

Of course, this wouldn't make sense if you're using opencv3 for other tasks, in which case you'd have to unlink to switch.  ¯\\_(ツ)_/¯
